version: "3"

services:
  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgresql:
    image: postgres:16
    env_file: ./.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: ./.env
    restart: always
    depends_on:
      - postgresql

  bot:
    build: ./bot
    env_file: ./.env
    restart: always
    depends_on:
      - postgresql
      - backend

volumes:
  postgres_data:
  redis_data:
